#!/usr/bin/perl

use strict;
use lib 'lib';
use Cwd;
use ShipIt;
use Getopt::Long;

my $opt_dry;
exit(1) unless
    GetOptions("dry-run|n"    => \$opt_dry,
               );

my $dir = shift || getcwd;
die "Usage: shipit [<dir>]\n" unless -d $dir;
chdir($dir) or die "Failed to chdir to $dir\n";

use File::Temp qw(tempdir);
my $tmpdir = tempdir();
my $conf = bless(
    {
        'val' => {
            'steps' =>
'FindVersion, ChangeVersion, CheckChangeLog, DistTest, Commit, Tag, MakeDist, CPANTS, UploadCPAN',
            'MakeDist.destination' => $tmpdir,
            'git.push_to' => 'origin',
        },
        'asked' => {}
    },
    'ShipIt::Conf'
);
my $state = ShipIt::State->new($conf);
$state->set_dry_run($opt_dry);

foreach my $step ($conf->steps) {
    warn "Running step $step\n";
    $step->run($state);
}

=head1 NAME

shipit - Executable for ShipIt

=head1 SYNOPSIS

 $ shipit
 $ shipit --dry-run       # or -n
 $ shipit --write-config
 $ shipit --skip-tests    # but please don't.

=head1 SEE ALSO

L<ShipIt>

L<ShipIt::Conf>

=head1 AUTHOR

Brad Fitzpatrick, et al.  (see AUTHORS file)

=head1 CONTRIBUTING

If you'd like to contribute to ShipIt (with either a bug report or patch), see:

L<http://contributing.appspot.com/shipit>

=head1 COPYRIGHT, LICENSE, and WARRANTY

ShipIt is copyright 2007 by SixApart, Ltd.

It's licensed under the same terms as Perl itself.

ShipIt comes with no warranty, either expressed or implied.
